type CountryType = {
  name: string;
  code: string;
  dialCode: string;
};

export const Supported_Countries: CountryType[] = [
  { name: "United States", code: "US", dialCode: "+1" },
  { name: "United Kingdom", code: "GB", dialCode: "+44" },
  { name: "Canada", code: "CA", dialCode: "+1" },
  { name: "Australia", code: "AU", dialCode: "+61" },
  { name: "Germany", code: "DE", dialCode: "+49" },
  { name: "France", code: "FR", dialCode: "+33" },
  { name: "Japan", code: "JP", dialCode: "+81" },
  { name: "China", code: "CN", dialCode: "+86" },
  { name: "India", code: "IN", dialCode: "+91" },
  { name: "Brazil", code: "BR", dialCode: "+55" },
  { name: "Russia", code: "RU", dialCode: "+7" },
  { name: "South Africa", code: "ZA", dialCode: "+27" },
  { name: "Italy", code: "IT", dialCode: "+39" },
  { name: "Mexico", code: "MX", dialCode: "+52" },
  { name: "South Korea", code: "KR", dialCode: "+82" },
  { name: "Saudi Arabia", code: "SA", dialCode: "+966" },
  { name: "Argentina", code: "AR", dialCode: "+54" },
  { name: "Nigeria", code: "NG", dialCode: "+234" },
  { name: "Spain", code: "ES", dialCode: "+34" },
  { name: "Turkey", code: "TR", dialCode: "+90" },
  { name: "Indonesia", code: "ID", dialCode: "+62" },
  { name: "New Zealand", code: "NZ", dialCode: "+64" },
  { name: "Philippines", code: "PH", dialCode: "+63" },
  { name: "Pakistan", code: "PK", dialCode: "+92" },
  { name: "Bangladesh", code: "BD", dialCode: "+880" },
  { name: "Vietnam", code: "VN", dialCode: "+84" },
  { name: "Thailand", code: "TH", dialCode: "+66" },
  { name: "Egypt", code: "EG", dialCode: "+20" },
  { name: "Ukraine", code: "UA", dialCode: "+380" },
  { name: "Malaysia", code: "MY", dialCode: "+60" },
  { name: "Poland", code: "PL", dialCode: "+48" },
  { name: "Netherlands", code: "NL", dialCode: "+31" },
  { name: "Sweden", code: "SE", dialCode: "+46" },
  { name: "Switzerland", code: "CH", dialCode: "+41" },
  { name: "Belgium", code: "BE", dialCode: "+32" },
  { name: "Norway", code: "NO", dialCode: "+47" },
  { name: "Denmark", code: "DK", dialCode: "+45" },
  { name: "Finland", code: "FI", dialCode: "+358" },
  { name: "Austria", code: "AT", dialCode: "+43" },
  { name: "Ireland", code: "IE", dialCode: "+353" },
  { name: "Israel", code: "IL", dialCode: "+972" },
  { name: "Singapore", code: "SG", dialCode: "+65" },
  { name: "Hong Kong", code: "HK", dialCode: "+852" },
  { name: "Portugal", code: "PT", dialCode: "+351" },
  { name: "Greece", code: "GR", dialCode: "+30" },
  { name: "Chile", code: "CL", dialCode: "+56" },
  { name: "Colombia", code: "CO", dialCode: "+57" },
  { name: "Peru", code: "PE", dialCode: "+51" },
  { name: "Venezuela", code: "VE", dialCode: "+58" },
  { name: "Czech Republic", code: "CZ", dialCode: "+420" },
  { name: "Romania", code: "RO", dialCode: "+40" },
  { name: "Hungary", code: "HU", dialCode: "+36" },
  { name: "Slovakia", code: "SK", dialCode: "+421" },
  { name: "Bulgaria", code: "BG", dialCode: "+359" },
  { name: "United Arab Emirates", code: "AE", dialCode: "+971" },
  { name: "Qatar", code: "QA", dialCode: "+974" },
  { name: "Kuwait", code: "KW", dialCode: "+965" },
  { name: "Oman", code: "OM", dialCode: "+968" },
  { name: "Bahrain", code: "BH", dialCode: "+973" },
  { name: "Morocco", code: "MA", dialCode: "+212" },
  { name: "Kenya", code: "KE", dialCode: "+254" },
  { name: "Ethiopia", code: "ET", dialCode: "+251" },
  { name: "Ghana", code: "GH", dialCode: "+233" },
  { name: "Uganda", code: "UG", dialCode: "+256" },
  { name: "Tanzania", code: "TZ", dialCode: "+255" },
  { name: "Algeria", code: "DZ", dialCode: "+213" },
  { name: "Ivory Coast", code: "CI", dialCode: "+225" },
  { name: "Senegal", code: "SN", dialCode: "+221" },
  { name: "Sudan", code: "SD", dialCode: "+249" },
  { name: "Zambia", code: "ZM", dialCode: "+260" },
  { name: "Zimbabwe", code: "ZW", dialCode: "+263" },
  { name: "Botswana", code: "BW", dialCode: "+267" },
  { name: "Namibia", code: "NA", dialCode: "+264" }
];
