type CountryType = {
  name: string;
  code: string;
  dialCode: string;
  currencyCode: string;
  currencySymbol: string;
};

export const Supported_Countries: CountryType[] = [
  {
    name: "United States",
    code: "US",
    dialCode: "+1",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  {
    name: "Canada",
    code: "CA",
    dialCode: "+1",
    currencyCode: "CAD",
    currencySymbol: "$",
  },
  {
    name: "United Kingdom",
    code: "GB",
    dialCode: "+44",
    currencyCode: "GBP",
    currencySymbol: "£",
  },
  {
    name: "France",
    code: "FR",
    dialCode: "+33",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Spain",
    code: "ES",
    dialCode: "+34",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Ireland",
    code: "IE",
    dialCode: "+353",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Netherlands",
    code: "NL",
    dialCode: "+31",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Germany",
    code: "DE",
    dialCode: "+49",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Italy",
    code: "IT",
    dialCode: "+39",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Poland",
    code: "PL",
    dialCode: "+48",
    currencyCode: "PLN",
    currencySymbol: "zł",
  },
  {
    name: "Denmark",
    code: "DK",
    dialCode: "+45",
    currencyCode: "DKK",
    currencySymbol: "kr",
  },
  {
    name: "Norway",
    code: "NO",
    dialCode: "+47",
    currencyCode: "NOK",
    currencySymbol: "kr",
  },
  {
    name: "Sweden",
    code: "SE",
    dialCode: "+46",
    currencyCode: "SEK",
    currencySymbol: "kr",
  },
  {
    name: "Estonia",
    code: "EE",
    dialCode: "+372",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Lithuania",
    code: "LT",
    dialCode: "+370",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Latvia",
    code: "LV",
    dialCode: "+371",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Portugal",
    code: "PT",
    dialCode: "+351",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Belgium",
    code: "BE",
    dialCode: "+32",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  {
    name: "Ghana",
    code: "GH",
    dialCode: "+233",
    currencyCode: "GHS",
    currencySymbol: "₵",
  },
  {
    name: "Australia",
    code: "AU",
    dialCode: "+61",
    currencyCode: "AUD",
    currencySymbol: "$",
  },
  {
    name: "Japan",
    code: "JP",
    dialCode: "+81",
    currencyCode: "JPY",
    currencySymbol: "¥",
  },
  {
    name: "South Korea",
    code: "KR",
    dialCode: "+82",
    currencyCode: "KRW",
    currencySymbol: "₩",
  },
  {
    name: "Switzerland",
    code: "CH",
    dialCode: "+41",
    currencyCode: "CHF",
    currencySymbol: "CHF",
  },
  {
    name: "Singapore",
    code: "SG",
    dialCode: "+65",
    currencyCode: "SGD",
    currencySymbol: "$",
  },
  {
    name: "Hong Kong",
    code: "HK",
    dialCode: "+852",
    currencyCode: "HKD",
    currencySymbol: "$",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    dialCode: "+971",
    currencyCode: "AED",
    currencySymbol: "د.إ",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    dialCode: "+966",
    currencyCode: "SAR",
    currencySymbol: "ر.س",
  },
  {
    name: "Qatar",
    code: "QA",
    dialCode: "+974",
    currencyCode: "QAR",
    currencySymbol: "ر.ق",
  },
];
