export type ProfessionCategory = {
  category: string;
  professions: string[];
};

export const ProfessionsByCategory: ProfessionCategory[] = [
  {
    category: "Students",
    professions: ["Student"],
  },
  {
    category: "Arts & Entertainment",
    professions: [
      "Actor",
      "Musician",
      "Painter",
      "Dancer",
      "Photographer",
      "Filmmaker",
      "Comedian",
      "Writer",
      "Fashion Designer",
      "Graphic Designer",
    ],
  },
  {
    category: "Science & Technology",
    professions: [
      "Scientist",
      "Engineer",
      "Software Developer",
      "Data Scientist",
      "Physicist",
      "Biologist",
      "Astronomer",
      "Mathematician",
      "Roboticist",
      "Web Developer",
    ],
  },
  {
    category: "Medicine & Healthcare",
    professions: [
      "Doctor",
      "Surgeon",
      "Nurse",
      "Pharmacist",
      "Veterinarian",
      "Dentist",
      "Therapist",
      "Psychologist",
      "Nutritionist",
      "Radiologist",
    ],
  },
  {
    category: "Sports",
    professions: [
      "Football Player",
      "Basketball Player",
      "Cricketer",
      "Tennis Player",
      "Gymnast",
      "Swimmer",
      "Runner",
      "Martial Artist",
      "Golfer",
      "Coach",
    ],
  },
  {
    category: "Business & Finance",
    professions: [
      "Entrepreneur",
      "Investor",
      "Accountant",
      "Banker",
      "Financial Analyst",
      "Marketing Manager",
      "Sales Executive",
      "HR Manager",
      "Economist",
      "Consultant",
    ],
  },
  {
    category: "Education",
    professions: [
      "Teacher",
      "Professor",
      "Researcher",
      "Librarian",
      "Education Consultant",
      "Tutor",
      "Curriculum Developer",
      "School Administrator",
    ],
  },
  {
    category: "Law & Public Services",
    professions: [
      "Lawyer",
      "Judge",
      "Police Officer",
      "Firefighter",
      "Politician",
      "Diplomat",
      "Social Worker",
      "Army Officer",
      "Public Administrator",
    ],
  },
  {
    category: "Trades & Crafts",
    professions: [
      "Carpenter",
      "Electrician",
      "Plumber",
      "Mechanic",
      "Chef",
      "Baker",
      "Hairdresser",
      "Tailor",
      "Blacksmith",
      "Farmer",
    ],
  },
  {
    category: "Aviation & Space",
    professions: [
      "Pilot",
      "Astronaut",
      "Air Traffic Controller",
      "Aircraft Engineer",
      "Aerospace Technician",
    ],
  },
  {
    category: "Media & Communication",
    professions: [
      "Journalist",
      "Editor",
      "Radio Host",
      "TV Anchor",
      "Public Relations Specialist",
      "Content Creator",
      "Social Media Manager",
      "Blogger",
      "Podcaster",
    ],
  },
];
